import '../models/user_model.dart';
import '../models/document_model.dart';
import '../models/extracted_data_model.dart';
import '../models/notification_model.dart';
import '../models/chat_message_model.dart';

class MockDataService {
  MockDataService._();

  // ─── Mock User ───
  static final UserModel mockUser = UserModel(
    id: 'usr_001',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    createdAt: DateTime(2025, 6, 15),
    totalDocuments: 12,
    totalQueries: 47,
  );

  // ─── Mock Documents ───
  static final List<DocumentModel> mockDocuments = [
    DocumentModel(
      id: 'doc_001',
      name: 'PAN Card',
      type: 'PAN Card',
      category: 'Identity',
      uploadDate: DateTime(2025, 12, 10),
      fileSize: 245760,
      tags: ['identity', 'tax', 'pan'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_002',
      name: 'Aadhaar Card',
      type: 'Aadhaar Card',
      category: 'Identity',
      uploadDate: DateTime(2025, 11, 20),
      fileSize: 512000,
      tags: ['identity', 'aadhaar', 'government'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_003',
      name: 'Passport',
      type: 'Passport',
      category: 'Identity',
      uploadDate: DateTime(2025, 10, 5),
      expiryDate: DateTime(2032, 1, 9),
      fileSize: 1048576,
      tags: ['identity', 'passport', 'travel'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_004',
      name: 'Driving License',
      type: 'Driving License',
      category: 'Identity',
      uploadDate: DateTime(2025, 9, 15),
      expiryDate: DateTime(2026, 3, 15),
      fileSize: 358400,
      tags: ['identity', 'license', 'driving'],
      isOfflineAvailable: true,
      status: 'expiring',
    ),
    DocumentModel(
      id: 'doc_005',
      name: 'B.Tech Degree Certificate',
      type: 'Degree Certificate',
      category: 'Education',
      uploadDate: DateTime(2025, 8, 20),
      fileSize: 2097152,
      tags: ['education', 'degree', 'btech'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_006',
      name: 'Final Year Marksheet',
      type: 'Marksheet',
      category: 'Education',
      uploadDate: DateTime(2025, 8, 20),
      fileSize: 1572864,
      tags: ['education', 'marksheet', 'grades'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_007',
      name: 'Health Insurance Policy',
      type: 'Insurance Policy',
      category: 'Insurance',
      uploadDate: DateTime(2025, 7, 10),
      expiryDate: DateTime(2026, 3, 25),
      fileSize: 3145728,
      tags: ['insurance', 'health', 'policy'],
      isOfflineAvailable: true,
      status: 'expiring',
    ),
    DocumentModel(
      id: 'doc_008',
      name: 'ITR 2024-25',
      type: 'Income Tax Return',
      category: 'Finance',
      uploadDate: DateTime(2025, 7, 31),
      fileSize: 819200,
      tags: ['finance', 'tax', 'itr'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_009',
      name: 'Salary Slip - January 2026',
      type: 'Salary Slip',
      category: 'Finance',
      uploadDate: DateTime(2026, 2, 1),
      fileSize: 204800,
      tags: ['finance', 'salary', 'payslip'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_010',
      name: 'Medical Test Report',
      type: 'Medical Report',
      category: 'Medical',
      uploadDate: DateTime(2026, 1, 15),
      fileSize: 4194304,
      tags: ['medical', 'health', 'report'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_011',
      name: 'Birth Certificate',
      type: 'Birth Certificate',
      category: 'Legal',
      uploadDate: DateTime(2025, 6, 20),
      fileSize: 614400,
      tags: ['legal', 'birth', 'certificate'],
      isOfflineAvailable: true,
      status: 'active',
    ),
    DocumentModel(
      id: 'doc_012',
      name: 'Voter ID Card',
      type: 'Voter ID',
      category: 'Identity',
      uploadDate: DateTime(2025, 5, 10),
      fileSize: 307200,
      tags: ['identity', 'voter', 'election'],
      isOfflineAvailable: true,
      status: 'active',
    ),
  ];

  // ─── Mock Extracted Data ───
  static final List<ExtractedDataModel> mockExtractedData = [
    ExtractedDataModel(
      id: 'ext_001',
      documentId: 'doc_001',
      documentName: 'PAN Card',
      documentType: 'PAN Card',
      category: 'Identity',
      data: {
        'PAN Number': 'ABCDE1234F',
        'Full Name': 'RAHUL SHARMA',
        'Father\'s Name': 'SURESH SHARMA',
        'Date of Birth': '15/03/1995',
        'Card Type': 'Individual',
      },
      extractedAt: DateTime(2025, 12, 10),
    ),
    ExtractedDataModel(
      id: 'ext_002',
      documentId: 'doc_002',
      documentName: 'Aadhaar Card',
      documentType: 'Aadhaar Card',
      category: 'Identity',
      data: {
        'Aadhaar Number': '1234 5678 9012',
        'Full Name': 'Rahul Sharma',
        'Date of Birth': '15/03/1995',
        'Gender': 'Male',
        'Address': '42, Marine Drive, Mumbai, MH 400001',
        'VID': '8765 4321 0987 6543',
      },
      extractedAt: DateTime(2025, 11, 20),
    ),
    ExtractedDataModel(
      id: 'ext_003',
      documentId: 'doc_003',
      documentName: 'Passport',
      documentType: 'Passport',
      category: 'Identity',
      data: {
        'Passport Number': 'J8765432',
        'Full Name': 'RAHUL SHARMA',
        'Nationality': 'Indian',
        'Date of Birth': '15/03/1995',
        'Place of Birth': 'Mumbai',
        'Date of Issue': '10/01/2022',
        'Date of Expiry': '09/01/2032',
        'Place of Issue': 'Mumbai',
      },
      extractedAt: DateTime(2025, 10, 5),
    ),
    ExtractedDataModel(
      id: 'ext_004',
      documentId: 'doc_004',
      documentName: 'Driving License',
      documentType: 'Driving License',
      category: 'Identity',
      data: {
        'License Number': 'MH01-2020-0012345',
        'Full Name': 'RAHUL SHARMA',
        'Date of Birth': '15/03/1995',
        'Blood Group': 'B+',
        'Vehicle Class': 'LMV, MCWG',
        'Date of Issue': '15/03/2020',
        'Valid Until': '15/03/2026',
        'Issuing Authority': 'RTO Mumbai',
      },
      extractedAt: DateTime(2025, 9, 15),
    ),
    ExtractedDataModel(
      id: 'ext_005',
      documentId: 'doc_005',
      documentName: 'B.Tech Degree Certificate',
      documentType: 'Degree Certificate',
      category: 'Education',
      data: {
        'Degree': 'Bachelor of Technology',
        'Branch': 'Computer Science & Engineering',
        'University': 'Mumbai University',
        'Year of Passing': '2023',
        'Roll Number': 'MU-CS-2019-0456',
        'Grade': 'First Class with Distinction',
      },
      extractedAt: DateTime(2025, 8, 20),
    ),
    ExtractedDataModel(
      id: 'ext_006',
      documentId: 'doc_006',
      documentName: 'Final Year Marksheet',
      documentType: 'Marksheet',
      category: 'Education',
      data: {
        'CGPA': '8.7 / 10',
        'University': 'Mumbai University',
        'Program': 'B.Tech Computer Science',
        'Semester': '8th (Final)',
        'Total Credits': '172',
        'Year': '2023',
        'Result': 'PASSED',
      },
      extractedAt: DateTime(2025, 8, 20),
    ),
    ExtractedDataModel(
      id: 'ext_007',
      documentId: 'doc_007',
      documentName: 'Health Insurance Policy',
      documentType: 'Insurance Policy',
      category: 'Insurance',
      data: {
        'Policy Number': 'HI-2025-789456',
        'Policy Holder': 'Rahul Sharma',
        'Insurer': 'Star Health Insurance',
        'Sum Insured': '₹5,00,000',
        'Premium': '₹12,500/year',
        'Policy Start': '25/03/2025',
        'Policy End': '25/03/2026',
        'Coverage Type': 'Individual',
      },
      extractedAt: DateTime(2025, 7, 10),
    ),
    ExtractedDataModel(
      id: 'ext_008',
      documentId: 'doc_008',
      documentName: 'ITR 2024-25',
      documentType: 'Income Tax Return',
      category: 'Finance',
      data: {
        'Assessment Year': '2024-25',
        'PAN': 'ABCDE1234F',
        'Gross Income': '₹12,50,000',
        'Total Tax Paid': '₹1,87,500',
        'Filing Date': '31/07/2025',
        'ITR Form': 'ITR-1',
        'Verification Status': 'E-Verified',
      },
      extractedAt: DateTime(2025, 7, 31),
    ),
  ];

  // ─── Mock Notifications ───
  static final List<NotificationModel> mockNotifications = [
    NotificationModel(
      id: 'notif_001',
      title: 'Document Expiring Soon',
      body: 'Your Driving License will expire in 15 days. Please renew it before March 15, 2026.',
      type: NotificationType.expiry,
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
      documentId: 'doc_004',
    ),
    NotificationModel(
      id: 'notif_002',
      title: 'Insurance Policy Expiring',
      body: 'Your Health Insurance Policy will expire in 25 days. Renew to maintain coverage.',
      type: NotificationType.expiry,
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
      documentId: 'doc_007',
    ),
    NotificationModel(
      id: 'notif_003',
      title: 'Document Uploaded Successfully',
      body: 'Your Salary Slip - January 2026 has been uploaded and processed.',
      type: NotificationType.upload,
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      documentId: 'doc_009',
    ),
    NotificationModel(
      id: 'notif_004',
      title: 'Data Extraction Complete',
      body: 'Key information has been extracted from your Medical Test Report.',
      type: NotificationType.system,
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
      documentId: 'doc_010',
    ),
    NotificationModel(
      id: 'notif_005',
      title: 'New Login Detected',
      body: 'A new login was detected from your device. If this wasn\'t you, please secure your account.',
      type: NotificationType.security,
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    NotificationModel(
      id: 'notif_006',
      title: 'Document Uploaded Successfully',
      body: 'Your Medical Test Report has been uploaded and is being processed.',
      type: NotificationType.upload,
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      documentId: 'doc_010',
    ),
    NotificationModel(
      id: 'notif_007',
      title: 'Weekly Summary',
      body: 'You uploaded 3 documents this week. 2 documents are expiring soon.',
      type: NotificationType.system,
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
    ),
  ];

  // ─── Mock Chat Messages ───
  static final List<ChatMessageModel> mockChatMessages = [
    ChatMessageModel(
      id: 'msg_001',
      content: 'Hello! I\'m your document intelligence assistant. I can help you find information from your uploaded documents. What would you like to know?',
      isUser: false,
      timestamp: DateTime.now().subtract(const Duration(hours: 1)),
    ),
  ];

  // ─── Mock Recent Activity ───
  static final List<Map<String, dynamic>> mockRecentActivity = [
    {
      'action': 'Uploaded document',
      'detail': 'Salary Slip - January 2026',
      'time': DateTime.now().subtract(const Duration(hours: 3)),
      'icon': 'upload',
    },
    {
      'action': 'Queried documents',
      'detail': 'What is my PAN number?',
      'time': DateTime.now().subtract(const Duration(hours: 6)),
      'icon': 'chat',
    },
    {
      'action': 'Viewed document',
      'detail': 'Passport',
      'time': DateTime.now().subtract(const Duration(days: 1)),
      'icon': 'view',
    },
    {
      'action': 'Uploaded document',
      'detail': 'Medical Test Report',
      'time': DateTime.now().subtract(const Duration(days: 2)),
      'icon': 'upload',
    },
    {
      'action': 'Data extracted',
      'detail': 'ITR 2024-25 processed',
      'time': DateTime.now().subtract(const Duration(days: 3)),
      'icon': 'extract',
    },
  ];
}
